name: GuardRail.js Security Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display Banner
        run: |
          echo "GuardRail.js Security Pipeline"
          echo "🛡️ Starting security checks..."

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run Security Tests
        run: npm run test:security

      - name: Run ESLint Security Checks
        run: npm run lint:security

      - name: Generate Security Report
        run: npm run security:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: reports/security-report.md
